// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeKSlcMRL33csBmKCmk2IY6-P3C9Ip59Y',
    appId: '1:556680307011:ios:f82931ec2c20d3af6d4ff6',
    messagingSenderId: '556680307011',
    projectId: 'dailypluse-39bc5',
    storageBucket: 'dailypluse-39bc5.firebasestorage.app',
    iosBundleId: 'com.example.dailyPluse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBskEtvW5GvLDAmlwgLq5aTE8-lnI5nN3c',
    appId: '1:556680307011:web:d27089dd5cea6f036d4ff6',
    messagingSenderId: '556680307011',
    projectId: 'dailypluse-39bc5',
    authDomain: 'dailypluse-39bc5.firebaseapp.com',
    storageBucket: 'dailypluse-39bc5.firebasestorage.app',
    measurementId: 'G-VQSLD9NQ29',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBskEtvW5GvLDAmlwgLq5aTE8-lnI5nN3c',
    appId: '1:556680307011:web:d27089dd5cea6f036d4ff6',
    messagingSenderId: '556680307011',
    projectId: 'dailypluse-39bc5',
    authDomain: 'dailypluse-39bc5.firebaseapp.com',
    storageBucket: 'dailypluse-39bc5.firebasestorage.app',
    measurementId: 'G-VQSLD9NQ29',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeKSlcMRL33csBmKCmk2IY6-P3C9Ip59Y',
    appId: '1:556680307011:ios:f82931ec2c20d3af6d4ff6',
    messagingSenderId: '556680307011',
    projectId: 'dailypluse-39bc5',
    storageBucket: 'dailypluse-39bc5.firebasestorage.app',
    iosBundleId: 'com.example.dailyPluse',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRtqJktCJjhuMFflXtf5bQVy1k7KKyx_s',
    appId: '1:556680307011:android:a7cfbdc81c0248906d4ff6',
    messagingSenderId: '556680307011',
    projectId: 'dailypluse-39bc5',
    storageBucket: 'dailypluse-39bc5.firebasestorage.app',
  );

}